//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeStore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FakeStore.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string idAll {
            get {
                return ResourceManager.GetString("idAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string idCategory {
            get {
                return ResourceManager.GetString("idCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:  .
        /// </summary>
        internal static string idCategoryColonSpaceSpace {
            get {
                return ResourceManager.GetString("idCategoryColonSpaceSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string idCount {
            get {
                return ResourceManager.GetString("idCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:  .
        /// </summary>
        internal static string idCountColonSpaceSpace {
            get {
                return ResourceManager.GetString("idCountColonSpaceSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string idDollarSign {
            get {
                return ResourceManager.GetString("idDollarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string idEmail {
            get {
                return ResourceManager.GetString("idEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string idError {
            get {
                return ResourceManager.GetString("idError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address to login..
        /// </summary>
        internal static string idInvalidEmail {
            get {
                return ResourceManager.GetString("idInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password of at least 5 characters to login..
        /// </summary>
        internal static string idInvalidPassord {
            get {
                return ResourceManager.GetString("idInvalidPassord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string idLogout {
            get {
                return ResourceManager.GetString("idLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string idNone {
            get {
                return ResourceManager.GetString("idNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string idOk {
            get {
                return ResourceManager.GetString("idOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string idPassword {
            get {
                return ResourceManager.GetString("idPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string idPrice {
            get {
                return ResourceManager.GetString("idPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string idRating {
            get {
                return ResourceManager.GetString("idRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:  .
        /// </summary>
        internal static string idRatingColonSpaceSpace {
            get {
                return ResourceManager.GetString("idRatingColonSpaceSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        internal static string idSortBy {
            get {
                return ResourceManager.GetString("idSortBy", resourceCulture);
            }
        }
    }
}
